import Head from 'next/head'
import { Fragment, useEffect } from 'react';
import React, { useState } from 'react';
import DynamicKit from '../components/dynamicKit'

export default function Home() {

  const submitContact = async (event) => {
    
    event.preventDefault();
    // <DynamicKit />
    console.log(document.getElementById("name").value);

    let div = document.createElement('div');
    div.id = "kit";
    //div.innerText = document.getElementById('name').value + document.getElementById('number').value; 
    // div.innerHTML = <DynamicKit />;
    document.body.appendChild(div);

    
  };
  
  return (
    <Fragment>
      <div id='home'>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon.png"></link>
          <meta name="theme-color" content="#fff" />
        </Head>

          <div className="max-w-xs my-2 overflow-hidden rounded shadow-lg">
            <div className="px-6 py-4">
              <div className="mb-2 text-xl font-bold text-black">Contact us</div>
              <form className="flex flex-col" onSubmit={submitContact}>
                <label htmlFor="name" className="mb-2 italic text-black">Name & number</label>
                <input
                  className="mb-4 border-b-2"
                  id="name"
                  name="name"
                  type="text"
                  autoComplete="name"
                  required
                />
                <input
                  className="mb-4 border-b-2"
                  id="number"
                  name="number"
                  type="text"
                  required
                />
                <button
                  type="submit"
                  className="px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700"
                >
                  Submit
                </button>
              </form>
            </div>
          </div>
      </div>
    </Fragment>
  )
}
