import Head from 'next/head'
import { Fragment } from 'react';
import React from 'react';
import NavBar from '../components/navBar';

export default function Home() {
  
  const submitContact = async (event) => {
    
    event.preventDefault();
    console.log(document.getElementById("name").value);

    let biggerParentDiv = document.createElement('div');
    biggerParentDiv.className = "parentKit"; //parent div 

    let parentDiv = document.createElement('div');
    parentDiv.className = "kit"; //div to display the kit

    parentDiv.style.filter ="brightness(0.5) sepia(1) saturate(10000%) hue-rotate(" + document.getElementById('color').value + "deg)"; //filter code to give kit color

    if(document.getElementById('color').value < 0) { //if statement for when user wants harder to filter colors
      console.log("hi")
      if(document.getElementById('color').value == "-10"){ //black
        parentDiv.style.filter ="brightness(0)";
      }
      else if (document.getElementById('color').value == "-20") { //orange
        parentDiv.style.filter = "invert(74%) sepia(100%) saturate(2206%) hue-rotate(16deg) brightness(114%) contrast(118%)"; //used https://codepen.io/jumarjuaton/full/mdJYWYq generator
      }
      else if (document.getElementById('color').value == "-30") { //yellow
        console.log("hello...")
        parentDiv.style.filter = "invert(82%) sepia(74%) saturate(614%) hue-rotate(3deg) brightness(1198%) contrast(108%)";
      }
      else { //white
        parentDiv.style.filter ="brightness(1)";
      }
    }


    let childDivName = document.createElement('div');
    let childDivNumber = document.createElement('div');
    childDivName.className = "kitName"; //div to display player name
    childDivNumber.className = "kitNumber"; //div to display player number

    childDivName.style.color = document.getElementById('textcolor').value; //use form value to define color
    childDivNumber.style.color = document.getElementById('textcolor').value;

    childDivName.innerText = document.getElementById('name').value;
    childDivNumber.innerText = document.getElementById('number').value; 
    biggerParentDiv.appendChild(parentDiv) 
    biggerParentDiv.appendChild(childDivName);
    biggerParentDiv.appendChild(childDivNumber);


    document.getElementById("home").appendChild(biggerParentDiv);
    document.getElementById('kitComponent').style.visibility = 'hidden'
    
  }

  const newKit = async (event) => {
    event.preventDefault();
    console.log('hewo');
    document.getElementById('kitComponent').style.visibility = 'visible';
  }

  
  ;
  
  return (
    <Fragment>
      <div id='home' className='pt-4'>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon.png"></link>
          <meta name="theme-color" content="#fff" />
        </Head>

        {/* top of the page DYNAMIC KIT COUNT */}
        <div className='dynaKitCount'>
          <div className='relative w-70% pt-4 text-text text-center font-bold'>SeenKits</div>
          <div className='relative w-70% pt-5 text-text text-center font-bold text-xxxl'>0</div>
        </div>

        {/* STAT BUBBLES */}
        <div className='flex grid grid-cols-1 content-center mx-10 '>
          <div className='text-center border-b-2 border-lineBlue'>Top countries seen</div>
        </div>
        <div className='flex grid grid-cols-3 content-center mx-10 pt-2'>
          <div className='text-center rounded-full border-solid border-2 border-lightBlue w-24 pt-0 mx-auto'>
            <div className='my-5 text-xxxl'>
              0
            </div>
          </div>
          <div className='text-center rounded-full border-solid border-2 border-lightBlue w-24 pt-0 mx-auto'>
            <div className='my-5 text-xxxl'>
              0
            </div>
          </div>
          <div className='text-center rounded-full border-solid border-2 border-lightBlue w-24 pt-0 mx-auto'>
            <div className='my-5 text-xxxl'>
              0
            </div>
          </div>
          <div className='text-center text-sm mt-1'>Country</div>
          <div className='text-center text-sm mt-1'>Country</div>
          <div className='text-center text-sm mt-1'>Country</div>
        </div>

        {/* RECENT KITS */}
        <div className='flex grid grid-cols-1 content-center mx-10 pt-6'>
          <div className='text-center border-b-2 border-lineBlue'>Recent kits</div>
        </div>
        <div className='flex grid grid-cols-3 content-center mx-10 pt-2'>
          <div className='showKits w-22 h-28 pt-0 mx-auto text-center'>
            <button className='my-5 text-xxxl text-text' onClick={newKit}>
              +
            </button>
          </div>
          {/* brightness(0.5) sepia(1) saturate(10000%) hue-rotate(" + document.getElementById('color').value + "deg) */}
          <div className='showKits w-22 h-28 pt-0 mx-auto text-center'>
            <div className='relative pt-3 text-text text-center text-sm font-bold'>Salah</div>
            <div className='relative pt-4 text-text text-center text-xl font-bold text-xxxl'>11</div>
          </div>
          <div className='showKits w-22 h-28 pt-0 mx-auto text-center'>
            <div className='relative pt-3 text-text text-center text-sm font-bold'>Messi</div>
            <div className='relative pt-4 text-text text-center text-xl font-bold text-xxxl'>10</div>
          </div>
          <div className='text-center text-sm mt-1'>New kit</div>
          <div className='text-center text-sm mt-1'>Liverpool</div>
          <div className='text-center text-sm mt-1'>PSG</div>
        </div>
        

        {/* CREATE NEW KIT COMPONENT */}
        <div className='relative inline-block h-max bottom-96'>
          <div className="kitComponent absolute max-w-xs my-2 shadow-lg bg-text" id='kitComponent'> 
            <div className="px-6 py-4">
              <div className="mb-2 text-xl font-bold text-black text-center">New kit</div>
              <form className="flex flex-col" onSubmit={submitContact}>
                <label htmlFor="name" className="mb-2 italic text-black">Player name</label>
                <input
                  className="mb-4"
                  id="name"
                  name="name"
                  type="text"
                  autoComplete="name"
                  placeholder= "name"
                  required
                />
                <label htmlFor="name" className="mb-2 italic text-black">Kit number</label>
                <input
                  className="mb-4"
                  id="number"
                  name="number"
                  type="text"
                  placeholder={"number"}
                  required
                />
                <label htmlFor="name" className="mb-2 italic text-black">Kit main color</label>
                <select //https://www.quackit.com/css/functions/css_hue-rotate_function.cfm color wheel HUE RED
                //these options hold values for the color wheel. B&W hold values for the if statement.
                  className="mb-4"
                  id="color"
                  name="color"
                  required>
                    <option value="-10">Black</option> 
                    <option value="-100">White</option>
                    <option value="0">Red</option>
                    <option value="-20">Orange</option> 
                    <option value="-30">Yellow</option>
                    <option value="120">Green</option>
                    <option value="180">Light blue</option>
                    <option value="240">Blue</option>
                    <option value="270">Purple</option>
                    <option value="300">Pink</option>
                </select>
                
                <label htmlFor="name" className="mb-2 italic text-black">Text color</label>
                <select //https://www.quackit.com/css/functions/css_hue-rotate_function.cfm color wheel HUE RED
                //these options hold values for the color wheel. B&W hold values for the if statement.
                  className="mb-4"
                  id="textcolor"
                  name="textcolor"
                  required>
                    <option value="black">Black</option> 
                    <option value="white">White</option>
                    <option value="red">Red</option>
                    <option value="orange">Orange</option> 
                    <option value="yellow">Yellow</option>
                    <option value="green">Green</option>
                    <option value="blue">Blue</option>
                    <option value="purple">Purple</option>
                    <option value="pink">Pink</option>
                </select>
                <button
                  type="submit"
                  className="px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700"
                >
                  Submit
                </button>
              </form>
            </div>
          </div>
        </div>
          {/* END CREATE NEW KIT COMPONENT */}
          <NavBar />
      </div>
    </Fragment>
  )
}
